name: Deploy Spring Boot App to VPS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: List target directory
      run: ls -la target/

    - name: Debug VPS_HOST
      run: echo "VPS_HOST: ${{ secrets.VPS_HOST }}"  # Debugging VPS_HOST value

    - name: Deploy to VPS
      env:
        PRIVATE_KEY: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
      run: |
        echo "VPS_HOST: $VPS_HOST"  # Debugging VPS_HOST value
        
        # Install SSH client and SCP (just in case it's missing)
        sudo apt-get update
        sudo apt-get install -y openssh-client

        # Create SSH key directory
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Add the VPS to known hosts to avoid confirmation prompt
        ssh-keyscan -H $VPS_HOST >> ~/.ssh/known_hosts

        # List the target directory to verify the JAR file exists
        ls -la target/

        # Stop any existing Spring Boot application running on the VPS
        echo "Stopping existing Spring Boot application..."
        ssh $VPS_USER@$VPS_HOST 'pgrep -f "java -jar" | xargs -r kill -9'

        # Deploy the JAR file to VPS
        scp target/fitness-0.0.1-SNAPSHOT.jar $VPS_USER@$VPS_HOST:~/pg222-project/

        # SSH into the VPS, change to the pg222-project directory, and run the app in the background using nohup
        ssh $VPS_USER@$VPS_HOST 'cd ~/pg222-project && nohup java -jar fitness-0.0.1-SNAPSHOT.jar > nohup.out 2>&1 &'
